package com.heal.doctor.entity.models.enums;

public enum EntityPermission {
    ENTITY_READ,
    ENTITY_UPDATE,
    ENTITY_MANAGE_MEMBERS,

    AFFILIATION_INITIATE,
    AFFILIATION_ACCEPT,
    AFFILIATION_VIEW,
    AFFILIATION_MANAGE_AVAILABILITY,
    AFFILIATION_TERMINATE,

    STAFF_ASSIGN_ENTITY,
    STAFF_ASSIGN_DOCTOR,
    STAFF_REVOKE,
    STAFF_VIEW,

    APPOINTMENT_VIEW_ENTITY,
    APPOINTMENT_MANAGE_ENTITY,

    AFFILIATION_ADMIN_APPROVE
}
